# Thank you for Downloading EnvalliumAPI.
# This is either because your a developer
# OR a server owner who is using plugins that require this plugin
#
# This plugin has many features for both developers and server owners alike
# Wiki: Coming Soon
#
# If you have any enquires or found any bugs, dm me on discord Jay Dusk#1827